### ISSUE TITLE
Why you are not supported Java?

### ISSUE THREAD

**Issue by vietankur009** [MaxCDN/api-docs#26]
Hi,

I saw that you are supporting seven languages, but not Java. Is there any specific reason for doing that. Currently, I am working on a project where I want to flush MaxCDN cache using Java code, but there is no direct API support from your side. Is there any specific reason for not supporting java?

Regards
Ankur Chauhan

**Comment by jdorfman** [comment]
Hey @vietankur009 

The only reason we don't have one yet is that no one has asked for one until now.  Shoot me an email and we can discuss your project as well as a solution: jdorfman at maxcdn dot com

**Comment by jdorfman** [comment]
Hey @vietankur009 sorry for the delay.  Here you go: https://github.com/MaxCDN/java-maxcdn
